server {
    listen 8080;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;

    # 1. Rutas de React
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Puente a Despachos (AHORA AL PUERTO 8081)
    location /api/v1/despachos {
        proxy_pass http://10.0.11.62:8081/api/v1/despachos; 
    }

    # Puente a Ventas
    location /api/v1/ventas {
        proxy_pass http://10.0.11.62:8082/api/v1/ventas; 
    }
}
